version: "3.7"


services:

  ### Nginx ##############################################
  nginx_bot:
    container_name: bot_nginx
    build: ./nginx
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    depends_on:
      - backend_bot
    networks:
      - backend

### DB ##############################################
  dbbot:
    container_name: bot_db
    build:
      context: ./db
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend


### Gunicorn + Uvicorn + Aiohttp ##############################################
  backend_bot:
    restart: always
    env_file: .env
    tty: true
    container_name: bot_back
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - dbbot


networks:
  backend:
    driver: ${NETWORKS_DRIVER}
